name: billing_app_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  http: ^0.13.3
  pdf: ^3.11.3
  path_provider: ^2.1.4
  open_file_plus: ^3.4.1+1
  pay: ^1.1.0 # Google Pay support
  qr_flutter: ^4.1.0 # For generating QR codes
  intl: ^0.18.1 # For date formatting
  mongo_dart: ^0.10.0 # ✅ Added MongoDB support

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/qr_code.jpg  # ✅ Fixed folder name (changed "asserts" to "assets")
