name: billing_app_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  http: ^0.13.6  # Consider updating to ^0.14.0 or ^1.0.0
  pdf: ^3.11.3
  path_provider: ^2.1.4
  open_file_plus: ^3.4.1
  pay: ^1.1.0
  qr_flutter: ^4.1.0
  intl: ^0.18.1  # Consider updating if conflicts arise
  mongo_dart: ^0.10.0
  provider: ^6.1.0
  fl_chart: ^0.63.0
  hive: ^2.2.3  # ✅ Added Hive
  hive_flutter: ^1.1.0  # ✅ Added Hive Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/qr_code.jpg  # ✅ Indentation fixed
